version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - network
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: "${ZOOKEEPER_PORT}"
      ZOOKEEPER_TICK_TIME: 2000
  
  broker1:
    image: confluentinc/cp-kafka:latest
    container_name: broker1
    networks:
      - network
    hostname: ${KAFKA_HOST1}
    ports:
      - "${KAFKA_PORT1}:${KAFKA_PORT1}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "INTERNAL://${KAFKA_HOST1}:${KAFKA_PORT1}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://${KAFKA_HOST1}:${KAFKA_PORT1}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 
    depends_on:
      - zookeeper

  broker2:
    image: confluentinc/cp-kafka:latest
    container_name: broker2
    networks:
      - network
    hostname: ${KAFKA_HOST2}
    ports:
      - "${KAFKA_PORT2}:${KAFKA_PORT2}"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "INTERNAL://${KAFKA_HOST2}:${KAFKA_PORT2}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://${KAFKA_HOST2}:${KAFKA_PORT2}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 
    depends_on:
      - zookeeper

  broker3:
    image: confluentinc/cp-kafka:latest
    container_name: broker3
    networks:
      - network
    hostname: broker3
    ports:
      - "${KAFKA_PORT3}:${KAFKA_PORT3}"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "INTERNAL://${KAFKA_HOST3}:${KAFKA_PORT3}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://${KAFKA_HOST3}:${KAFKA_PORT3}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 
    depends_on:
      - zookeeper
 
  producer:
    container_name: producer
    networks:
      - network
    build:
      context: .
      dockerfile: ./data_streaming/kafka_producer/Dockerfile
    environment:
      KAFKA_HOST1: "${KAFKA_HOST1}"
      KAFKA_PORT1: "${KAFKA_PORT1}"
      KAFKA_HOST2: "${KAFKA_HOST2}"
      KAFKA_PORT2: "${KAFKA_PORT2}"
      KAFKA_HOST3: "${KAFKA_HOST3}"
      KAFKA_PORT3: "${KAFKA_PORT3}"
      SCHEDULES_INPUT_TOPIC: "${SCHEDULES_INPUT_TOPIC}"
      MBTA_API_KEY: "${MBTA_API_KEY}"
      PYTHONUNBUFFERED: 1
    depends_on:
      - broker1
      - broker2
      - broker3
 
  consumer:
    container_name: consumer
    networks:
      - network
    build:
      context: .
      dockerfile: ./data_streaming/kafka_consumer/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_DRIVER=${POSTGRES_DRIVER}
      - KAFKA_HOST1=${KAFKA_HOST1}
      - KAFKA_PORT1=${KAFKA_PORT1}
      - KAFKA_HOST2=${KAFKA_HOST2}
      - KAFKA_PORT2=${KAFKA_PORT2}
      - KAFKA_HOST3=${KAFKA_HOST3}
      - KAFKA_PORT3=${KAFKA_PORT3}
      - SCHEDULES_INPUT_TOPIC=${SCHEDULES_INPUT_TOPIC}
      - PYTHONUNBUFFERED=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true 
    depends_on:
      - broker1
      - broker2
      - broker3
      - flask_database
  
  flask_app:
    restart: always
    container_name: flask_app
    build:
      context: .
      dockerfile: ./flask_app/Dockerfile
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - DEV_POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - flask_database
 
  flask_database:
    container_name: flask_database
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: 

networks:
  network:
