version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    networks:
      - network
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: "${ZOOKEEPER_PORT}"
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test:
        ["CMD", "bash", "-c", "echo 'ruok' | nc zookeeper ${ZOOKEEPER_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
  broker1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker1
    networks:
      - network
    hostname: ${KAFKA_HOST1}
    ports:
      - "${KAFKA_PORT1}:${KAFKA_PORT1}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "INTERNAL://${KAFKA_HOST1}:${KAFKA_PORT1}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://${KAFKA_HOST1}:${KAFKA_PORT1}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z ${KAFKA_HOST1} ${KAFKA_PORT1}"]
      interval: 10s
      timeout: 5s
      retries: 5
  broker2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker2
    networks:
      - network
    hostname: ${KAFKA_HOST2}
    ports:
      - "${KAFKA_PORT2}:${KAFKA_PORT2}"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "INTERNAL://${KAFKA_HOST2}:${KAFKA_PORT2}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://${KAFKA_HOST2}:${KAFKA_PORT2}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z ${KAFKA_HOST2} ${KAFKA_PORT2}"]
      interval: 10s
      timeout: 5s
      retries: 5
  broker3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker3
    networks:
      - network
    hostname: broker3
    ports:
      - "${KAFKA_PORT3}:${KAFKA_PORT3}"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENERS: "INTERNAL://${KAFKA_HOST3}:${KAFKA_PORT3}"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://${KAFKA_HOST3}:${KAFKA_PORT3}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z ${KAFKA_HOST3} ${KAFKA_PORT3}"]
      interval: 10s
      timeout: 5s
      retries: 5
  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "${KAFKA_HOST1}:${KAFKA_PORT1},${KAFKA_HOST2}:${KAFKA_PORT2},${KAFKA_HOST3}:${KAFKA_PORT3}"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - network
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.0
    hostname: control-center
    container_name: control-center
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy
      schema-registry:
        condition: service_started
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "${KAFKA_HOST1}:${KAFKA_PORT1},${KAFKA_HOST2}:${KAFKA_PORT2},${KAFKA_HOST3}:${KAFKA_PORT3}"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONFLIENT_METRICS_ENABLE: "false"
      PORT: 9021
    networks:
      - network
  producer:
    container_name: producer
    networks:
      - network
    build:
      context: .
      dockerfile: ./data_streaming/kafka_producer/Dockerfile
    environment:
      KAFKA_HOST1: "${KAFKA_HOST1}"
      KAFKA_PORT1: "${KAFKA_PORT1}"
      KAFKA_HOST2: "${KAFKA_HOST2}"
      KAFKA_PORT2: "${KAFKA_PORT2}"
      KAFKA_HOST3: "${KAFKA_HOST3}"
      KAFKA_PORT3: "${KAFKA_PORT3}"
      MBTA_API_KEY: "${MBTA_API_KEY}"
      PYTHONUNBUFFERED: 1
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy
  consumer:
    container_name: consumer
    networks:
      - network
    build:
      context: .
      dockerfile: ./data_streaming/kafka_consumer/Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_DRIVER=${POSTGRES_DRIVER}
      - KAFKA_HOST1=${KAFKA_HOST1}
      - KAFKA_HOST2=${KAFKA_HOST2}
      - KAFKA_HOST3=${KAFKA_HOST3}
      - KAFKA_PORT1=${KAFKA_PORT1}
      - KAFKA_PORT2=${KAFKA_PORT2}
      - KAFKA_PORT3=${KAFKA_PORT3}
      - PYTHONUNBUFFERED=1
    depends_on:
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy
      flask_database:
        condition: service_healthy
  flask_app:
    restart: always
    container_name: flask_app
    networks:
      - network
    build:
      context: .
      dockerfile: ./flask_app/Dockerfile
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - DEV_POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - PYTHONUNBUFFERED=1
    depends_on:
      flask_database:
        condition: service_healthy
  flask_database:
    container_name: flask_database
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - network
volumes:
  postgres_data:
networks:
  network:
