version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT}"
      KAFKA_CREATE_TOPICS: "${SCHEDULES_INPUT_TOPIC}:1:1"

  kafka-producer:
    container_name: kafka-producer
    build:
      context: .
      dockerfile: ./data_streaming/kafka_producer/Dockerfile
    environment:
      KAFKA_HOST: "${KAFKA_HOST}"
      KAFKA_PORT: "${KAFKA_PORT}"
      SCHEDULES_INPUT_TOPIC: "${SCHEDULES_INPUT_TOPIC}"
      MBTA_API_KEY: "${MBTA_API_KEY}"
    depends_on:
      - kafka
