name: Deploy to Kubernetes

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "gcp auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Extract environment variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        
      - name: Configure gcloud CLI
        run: |
          gcloud config set project ac215-transit-prediction
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials cluster-1 --region us-central1-c --project ac215-transit-prediction

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.26.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/kompose

      - name: Deploy to Kubernetes
        run: |
             kubectl convert -f docker-compose.yml --out manifests
             kubectl apply -f manifests
