name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: python -m pip install black flake8 mypy

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          black_auto_fix : true
          flake8: true
